import type { AlignedWord } from "../types.js";
import type { QuranIndex } from "../quran/corpus.js";

function assTime(seconds: number): string {
  const centiseconds = Math.max(0, Math.round(seconds * 100));
  const hours = Math.floor(centiseconds / 360_000);
  const minutes = Math.floor((centiseconds % 360_000) / 6_000);
  const wholeSeconds = Math.floor((centiseconds % 6_000) / 100);
  const fraction = centiseconds % 100;
  return `${hours}:${String(minutes).padStart(2, "0")}:${String(wholeSeconds).padStart(2, "0")}.${String(fraction).padStart(2, "0")}`;
}

function escapeAss(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/{/g, "\\{").replace(/}/g, "\\}").replace(/\r?\n/g, " ");
}

const RTL_ISOLATE = "\u2067";
const POP_DIRECTIONAL_ISOLATE = "\u2069";
const LTR_EMBED = "\u202A";
const POP_DIRECTIONAL_FORMATTING = "\u202C";

function isolatedArabic(value: string): string {
  return `${RTL_ISOLATE}${escapeAss(value)}${POP_DIRECTIONAL_ISOLATE}`;
}

function contextLine(word: AlignedWord, index: QuranIndex, wordsPerCaption: number): string {
  const verse = index.verses.get(word.verseKey);
  if (!verse || wordsPerCaption === 1) {
    return `{\\c&H0000D7FF&\\b1}${isolatedArabic(word.arabic)}{\\c&H00FFFFFF&\\b0}`;
  }
  const active = Math.max(0, word.position - 1);
  const start = Math.floor(active / wordsPerCaption) * wordsPerCaption;
  const end = Math.min(verse.words.length, start + wordsPerCaption);

  // libass applies Unicode bidi after parsing inline highlight tags. Supplying
  // canonical Arabic order and relying on that pass can shuffle whole words.
  // Emit the desired visual order explicitly: later words first on the left,
  // the earliest word last on the right, while each word remains an RTL isolate.
  const line = verse.words
    .slice(start, end)
    .reverse()
    .map((item) => {
      const isolated = isolatedArabic(item.text.uthmani);
      return item.position === word.position
        ? `{\\c&H0000D7FF&\\b1}${isolated}{\\c&H00FFFFFF&\\b0}`
        : isolated;
    })
    .join("\u00A0");
  // The token sequence is intentionally left-to-right because its array was
  // reversed above; right-aligned placement makes the first recited word the
  // rightmost item on screen.
  return `${LTR_EMBED}${line}${POP_DIRECTIONAL_FORMATTING}`;
}

export function createAss(words: AlignedWord[], index: QuranIndex, wordsPerCaption = 1): string {
  if (!Number.isSafeInteger(wordsPerCaption) || wordsPerCaption < 1) {
    throw new Error("wordsPerCaption must be a positive integer.");
  }
  const header = `[Script Info]
; Generated by transcribe-quran
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Quran,Noto Naskh Arabic,88,&H00FFFFFF,&H0000D7FF,&H00101010,&H90000000,0,0,0,0,100,100,0,0,1,4,1,2,70,70,170,1
Style: Translation,Arial,34,&H00FFFFFF,&H00FFFFFF,&H00101010,&H90000000,0,0,0,0,100,100,0,0,1,3,1,2,90,90,105,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
  const events: string[] = [];
  for (const word of words) {
    const start = assTime(word.start);
    const end = assTime(Math.max(word.end, word.start + 0.08));
    events.push(`Dialogue: 0,${start},${end},Quran,,0,0,0,,${contextLine(word, index, wordsPerCaption)}`);
    events.push(
      `Dialogue: 1,${start},${end},Translation,,0,0,0,,${escapeAss(word.wordTranslation)}  •  ${word.verseKey}`,
    );
  }
  return header + events.join("\n") + "\n";
}
