import type { AlignedWord } from "../types.js";
import type { QuranIndex } from "../quran/corpus.js";

function assTime(seconds: number): string {
  const centiseconds = Math.max(0, Math.round(seconds * 100));
  const hours = Math.floor(centiseconds / 360_000);
  const minutes = Math.floor((centiseconds % 360_000) / 6_000);
  const wholeSeconds = Math.floor((centiseconds % 6_000) / 100);
  const fraction = centiseconds % 100;
  return `${hours}:${String(minutes).padStart(2, "0")}:${String(wholeSeconds).padStart(2, "0")}.${String(fraction).padStart(2, "0")}`;
}

function escapeAss(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/{/g, "\\{").replace(/}/g, "\\}").replace(/\r?\n/g, " ");
}

const RTL_ISOLATE = "\u2067";
const POP_DIRECTIONAL_ISOLATE = "\u2069";

function isolatedArabic(value: string): string {
  return `${RTL_ISOLATE}${escapeAss(value)}${POP_DIRECTIONAL_ISOLATE}`;
}

function contextLine(word: AlignedWord, index: QuranIndex, radius = 3): string {
  const verse = index.verses.get(word.verseKey);
  if (!verse) return `\u202B${isolatedArabic(word.arabic)}\u202C`;
  const active = Math.max(0, word.position - 1);
  const start = Math.max(0, active - radius);
  const end = Math.min(verse.words.length, active + radius + 1);
  const line = verse.words
    .slice(start, end)
    .map((item) => {
      const isolated = isolatedArabic(item.text.uthmani);
      return item.position === word.position
        ? `{\\c&H0000D7FF&\\b1}${isolated}{\\c&H00FFFFFF&\\b0}`
        : isolated;
    })
    .join("\u00A0");
  // Inline ASS color tags can split the Unicode bidi run. An explicit RTL
  // embedding preserves canonical Arabic word order around the active word.
  return `\u202B${line}\u202C`;
}

export function createAss(words: AlignedWord[], index: QuranIndex): string {
  const header = `[Script Info]
; Generated by transcribe-quran
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
ScaledBorderAndShadow: yes
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Quran,Noto Naskh Arabic,88,&H00FFFFFF,&H0000D7FF,&H00101010,&H90000000,0,0,0,0,100,100,0,0,1,4,1,3,70,70,170,1
Style: Translation,Arial,34,&H00FFFFFF,&H00FFFFFF,&H00101010,&H90000000,0,0,0,0,100,100,0,0,1,3,1,2,90,90,105,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
  const events: string[] = [];
  for (const word of words) {
    const start = assTime(word.start);
    const end = assTime(Math.max(word.end, word.start + 0.08));
    events.push(`Dialogue: 0,${start},${end},Quran,,0,0,0,,${contextLine(word, index)}`);
    events.push(
      `Dialogue: 1,${start},${end},Translation,,0,0,0,,${escapeAss(word.wordTranslation)}  •  ${word.verseKey}`,
    );
  }
  return header + events.join("\n") + "\n";
}
